### PR TITLE
Draft of main-text

### PR DESCRIPTION
**Pull request by dhimmel**
As per https://twitter.com/dhimmel/status/1185287391172448256:

> First draft of the Manufesto proposed via pull request https://github.com/manubot/manufesto/pull/2. Feedback welcome.
>
> The purpose is to envision the features of an ideal authoring+publishing platform. #Manubot has some of these features, but not others (i.e. future goals).

### CODE REVIEW

**Comment by dhimmel** [comment]
@agitter did you want to review the Manufesto draft?

It's certainly not complete or perfect. Will fix small things in the PR. Big things perhaps in subsequent PRs by me (or even better by others).

**Review by agitter — APPROVED** [review]
@dhimmel because I'm fully focused on two major November 1 deadlines, it may be best to merge this now and let it serve as a base.  Then you, me, or others could make PRs to refine it from there.  It will be nice to have a readable HTML version for anyone who is less familiar with reading the AppVeyor PDFs or Markdown previews in this pull request.

Are you using `#.` intentionally to avoid headers?  One advantage of making these sub-headers (at some appropriate level) is that it would generate a nice table of contents summarizing the main ideas.

**Comment by dhimmel** [comment]
> Are you using #. intentionally to avoid headers? One advantage of making these sub-headers (at some appropriate level) is that it would generate a nice table of contents summarizing the main ideas.

Numbered headings would probably be the way to go, for the TOC as well as anchors. Can do in subsequent PR since it takes some finesse to think of the right headings.

**Comment by dhimmel** [comment]
> it may be best to merge this now and let it serve as a base. Then you, me, or others could make PRs to refine it from there.

Good idea! I think that's a good model for encouraging contributions and a fast pace.

**Pull request merged**
